# Generated by Django 2.2.7 on 2019-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('isbn', models.CharField(max_length=50)),
                ('number_of_pages', models.PositiveIntegerField(default=0)),
                ('publisher', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('authors', models.ManyToManyField(related_name='book_list', to='book.Author')),
            ],
        ),
    ]
